/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo.spring.app;

import org.junit.Test;
import static org.junit.Assert.*;

public class TodoAppTest {
    @Test public void appHasAGreeting() {
        TodoApp classUnderTest = new TodoApp();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
